Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "gin")
Ingredient.create(name: "vodka")
Ingredient.create(name: "orange")
Ingredient.create(name: "apple")
Ingredient.create(name: "lime")
Ingredient.create(name: "coke")
Ingredient.create(name: "sprite")
